[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
# buildCommand = "pip3 install -U requirements.txt"

[deploy]
startCommand = "python3 main.py"
healthcheckPath = "/"
restartPolicyType = "NEVER"
healthcheckTimeout = 100
